### ISSUE TITLE
Incident creation

### ISSUE THREAD

**Issue by Flatken** [cosmoscout/csp-vestec#7]
Enable the possibility to configure an incident:

 - Number of simulation runs (int)
 - Configure the area of interest by setting the bounding box (lat,lng as float)
 - Set mosquito species (string)
 - Set disease of interest (string)

**Comment by octfx** [comment]
Region of interest and number of runs can be set when creating the incident

Mosquito species and disease of interest can be passed via an additional `IncidentConfigNode`.
